config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  get '/recent_activity/(:user)' => 'posts#recent_activity', as: :recent_activity
  get '/repositories/:user' => 'posts#repositories', as: :repositories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    isaiah = Octokit::Client.new(access_token: ENV["github_key"])
    @indy_ruby_basic_users = isaiah.search_users("language:ruby location:indianapolis", page: params[:page], sort: 'joined', order: 'asc')
    @pages = (@indy_ruby_basic_users[:total_count]/30.0).ceil
    @indy_ruby_advanced_users = @indy_ruby_basic_users[:items].map{ |this_user| Octokit.user(this_user.login) }
    @indy_ruby_users_recent_repos = @indy_ruby_basic_users[:items].map {}
  end

  def recent_activity
    @recent_activities = Octokit.user_events(params[:user], sort:'created_at')
    @recent_activities
  end

  def repositories
    repositories_search = Octokit.search_repos("user:#{params[:user]}", sort:'stars', per_page: 5, page: params[:page])
    @pages = (repositories_search[:total_count]/5.0).ceil
    @repositories = repositories_search[:items]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>APIConsume</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <h1 class="title">Indy RUBYists</h1>
      </div>



    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h4 class="row">
  <% @pages.times do |x| %>
    <%= link_to "Page #{x + 1}", page: x + 1 %> ||
  <% end %>
 </h4>

<% @indy_ruby_advanced_users.each do |user| %>
<div class="row user-row">
  <div class="col-md-2">
    <%= image_tag user.avatar_url, class:"img-responsive" %>
  </div>
  <div class="col-md-6 col-md-offset-1">
    <h3 class="row">Username: <%= link_to user.login, user.html_url %></h3>
    <h5 class="row"> <%= user.created_at.strftime("Joined Github on %b %d, %Y") %></h5>
    <h5 class="row">Total Repos: <%= (user.public_repos).to_i + (user.total_private_repos).to_i %></h5>
    <h5 class="row">Followers: <%= user.followers%></h5>
    <h5 class="row"><%= link_to 'Recent Activity', recent_activity_path(user: user.login)%> </h5>
    <h5 class="row"><%= link_to 'Repositories', repositories_path(user: user.login)%> </h5>
  </div>
</div>
<% end %>

app/views/posts/recent_activity.html.erb
<h2 class="row"> <%= params[:user] %>'s recent activity: </h2>
<% if @recent_activities == []%>
<h3 class="row oops-message">OOPS, <%= params[:user] %> doesn't have any recent activity!</h3>
<% end %>
<% @recent_activities.each do |recent_activity| %>
<div class="repo-row row">

<h3 class="col-md-10 col-md-offset-1"> Event: <%=recent_activity[:payload][:action] %> a <%=recent_activity[:type] %> </h3>
<h3 class="col-md-10 col-md-offset-1"> On: <%= recent_activity[:repo][:name] %> </h3>
<h3 class="col-md-10 col-md-offset-1"> <%= recent_activity[:created_at].strftime("on %b %e, %l:%M %p") %></h3>
</div>
<% end %>

app/views/posts/repositories.html.erb
<h2 class="row"><%= params[:user]%>'s Repositories</h2>

<h4 class="row">
  <% @pages.times do |x| %>
    <%= link_to "Page #{x + 1}", page: x + 1 %> ||
  <% end %>
 </h4>

<% @repositories.each do |repo| %>
<div class="row repo-row">
  <h2 class="col-md-10 col-md-offset-1">Repo Name: <%= link_to repo.name, repo.html_url %> </h2>
  <h5 class="col-md-10 col-md-offset-1">Description: <%= repo.description %> </h5>
  <h5 class="col-md-10 col-md-offset-1"><%= repo.created_at.strftime("Created: %b %d, %Y") %> </h5>
  <h5 class="col-md-10 col-md-offset-1"><%= repo.updated_at.strftime("Last updated: %b %d, %Y") %></h5>
  <h5 class="col-md-10 col-md-offset-1">Stars:<%= repo.watchers %> </h5>
</div>
<% end %>